### ISSUE TITLE
Love it

### ISSUE THREAD

**Issue by barnjamin** [xBacked-DAO/algorand-wallet-select#8]
First, thank you for open sourcing this! I just found it and it looks awesome!

I haven't had a chance to try it out yet but the qr code modal provided by WalletConnect doesn't (or didn't?) support iOS algorand wallet. I had to change mine to use the algorand fork.

Also the "here" link on the readme is 404ing currently.

Thanks again! I'm going to start referring folks here

**Comment by xroark** [comment]
Thank you very much for your kind words @barnjamin. Much appreciated.

We'll make sure to update the readme and support the official Algorand iOS wallet in future iterations. 

Great suggestions and good eye spotting them!
